on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: yarn install
      - run: yarn test
      - run: npm i -g microbundle
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: $
          access: "public"
